[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
for = "/.well-known/assetlinks.json"
[headers.values]
Cache-Control = '''
    public,
    max-age=0'''
Content-Type = "application/json"
X-Content-Type-Options = "nosniff"

[[redirects]]
from = "/.well-known/*"
to = "/well-known/:splat"
status = 200


[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable
    '''
